package homeWork2

import java.io.File

fun main() {

    val file1 = File("D:\\android1\\android1\\android1\\android1")
    val file1_1 = File("D:\\android1\\android1\\android1\\android1\\text1.txt")
    val file1_2 = File("D:\\android1\\android1\\android1\\android1\\text2.txt")
    val file1_3 = File("D:\\android1\\android1\\android1\\android1\\text3.txt")
    val file1_4 = File("D:\\android1\\android1\\android1\\android1\\text4.txt")
    file1.mkdirs()
    file1_1.createNewFile()
    file1_2.createNewFile()
    file1_3.createNewFile()
    file1_4.createNewFile()
    file1_1.writeText("Voxidjonov Abduxalil")
    file1_2.writeText("Voxidjonov Abduxalil")
    file1_3.writeText("Voxidjonov Abduxalil")
    file1_4.writeText("Voxidjonov Abduxalil")

    val file2 = File("D:\\android1\\android1\\android1\\android2")
    val file2_1 = File("D:\\android1\\android1\\android1\\android2\\text1.txt")
    val file2_2 = File("D:\\android1\\android1\\android1\\android2\\text2.txt")
    val file2_3 = File("D:\\android1\\android1\\android1\\android2\\text3.txt")
    val file2_4 = File("D:\\android1\\android1\\android1\\android2\\text3.txt")
    file2.mkdirs()
    file2_1.createNewFile()
    file2_2.createNewFile()
    file2_3.createNewFile()
    file2_4.createNewFile()
    file2_1.writeText("Voxidjonov Abduxalil")
    file2_2.writeText("Voxidjonov Abduxalil")
    file2_3.writeText("Voxidjonov Abduxalil")
    file2_4.writeText("Voxidjonov Abduxalil")

    val file3 = File("D:\\android1\\android1\\android1\\android3")
    val file3_1 = File("D:\\android1\\android1\\android1\\android3\\text1.txt")
    val file3_2 = File("D:\\android1\\android1\\android1\\android3\\text2.txt")
    val file3_3 = File("D:\\android1\\android1\\android1\\android3\\text3.txt")
    val file3_4 = File("D:\\android1\\android1\\android1\\android3\\text3.txt")
    file3.mkdirs()
    file3_1.createNewFile()
    file3_2.createNewFile()
    file3_3.createNewFile()
    file3_4.createNewFile()
    file3_1.writeText("Voxidjonov Abduxalil")
    file3_2.writeText("Voxidjonov Abduxalil")
    file3_3.writeText("Voxidjonov Abduxalil")
    file3_4.writeText("Voxidjonov Abduxalil")

    val file4 = File("D:\\android1\\android1\\android2\\android1")
    val file4_1 = File("D:\\android1\\android1\\android2\\android1\\text1.txt")
    val file4_2 = File("D:\\android1\\android1\\android2\\android1\\text2.txt")
    val file4_3 = File("D:\\android1\\android1\\android2\\android1\\text3.txt")
    val file4_4 = File("D:\\android1\\android1\\android2\\android1\\text4.txt")
    file4.mkdirs()
    file4_1.createNewFile()
    file4_2.createNewFile()
    file4_3.createNewFile()
    file4_4.createNewFile()
    file4_1.writeText("Voxidjonov Abduxalil")
    file4_2.writeText("Voxidjonov Abduxalil")
    file4_3.writeText("Voxidjonov Abduxalil")
    file4_4.writeText("Voxidjonov Abduxalil")

    val file5 = File("D:\\android1\\android1\\android2\\android2")
    val file5_1 = File("D:\\android1\\android1\\android2\\android2\\text1.txt")
    val file5_2 = File("D:\\android1\\android1\\android2\\android2\\text2.txt")
    val file5_3 = File("D:\\android1\\android1\\android2\\android2\\text3.txt")
    val file5_4 = File("D:\\android1\\android1\\android2\\android2\\text4.txt")
    file5.mkdirs()
    file5_1.createNewFile()
    file5_2.createNewFile()
    file5_3.createNewFile()
    file5_4.createNewFile()
    file5_1.writeText("Voxidjonov Abduxalil")
    file5_2.writeText("Voxidjonov Abduxalil")
    file5_3.writeText("Voxidjonov Abduxalil")
    file5_4.writeText("Voxidjonov Abduxalil")

    val file6 = File("D:\\android1\\android1\\android2\\android3")
    val file6_1 = File("D:\\android1\\android1\\android2\\android3\\text1.txt")
    val file6_2 = File("D:\\android1\\android1\\android2\\android3\\text2.txt")
    val file6_3 = File("D:\\android1\\android1\\android2\\android3\\text3.txt")
    val file6_4 = File("D:\\android1\\android1\\android2\\android3\\text4.txt")
    file6.mkdirs()
    file6_1.createNewFile()
    file6_2.createNewFile()
    file6_3.createNewFile()
    file6_4.createNewFile()
    file6_1.writeText("Voxidjonov Abduxalil")
    file6_2.writeText("Voxidjonov Abduxalil")
    file6_3.writeText("Voxidjonov Abduxalil")
    file6_4.writeText("Voxidjonov Abduxalil")

    val file7 = File("D:\\android1\\android2\\android1\\android1")
    val file7_1 = File("D:\\android1\\android2\\android1\\android1\\text1.txt")
    val file7_2 = File("D:\\android1\\android2\\android1\\android1\\text2.txt")
    val file7_3 = File("D:\\android1\\android2\\android1\\android1\\text3.txt")
    val file7_4 = File("D:\\android1\\android2\\android1\\android1\\text4.txt")
    file7.mkdirs()
    file7_1.createNewFile()
    file7_2.createNewFile()
    file7_3.createNewFile()
    file7_4.createNewFile()
    file7_1.writeText("Voxidjonov Abduxalil")
    file7_2.writeText("Voxidjonov Abduxalil")
    file7_3.writeText("Voxidjonov Abduxalil")
    file7_4.writeText("Voxidjonov Abduxalil")

    val file8 = File("D:\\android1\\android2\\android1\\android2")
    val file8_1 = File("D:\\android1\\android2\\android1\\android2\\text1.txt")
    val file8_2 = File("D:\\android1\\android2\\android1\\android2\\text2.txt")
    val file8_3 = File("D:\\android1\\android2\\android1\\android2\\text3.txt")
    val file8_4 = File("D:\\android1\\android2\\android1\\android2\\text4.txt")
    file8.mkdirs()
    file8_1.createNewFile()
    file8_2.createNewFile()
    file8_3.createNewFile()
    file8_4.createNewFile()
    file8_1.writeText("Voxidjonov Abduxalil")
    file8_2.writeText("Voxidjonov Abduxalil")
    file8_3.writeText("Voxidjonov Abduxalil")
    file8_4.writeText("Voxidjonov Abduxalil")

    val file9 = File("D:\\android1\\android2\\android1\\android3")
    val file9_1 = File("D:\\android1\\android2\\android1\\android3\\text1.txt")
    val file9_2 = File("D:\\android1\\android2\\android1\\android3\\text2.txt")
    val file9_3 = File("D:\\android1\\android2\\android1\\android3\\text3.txt")
    val file9_4 = File("D:\\android1\\android2\\android1\\android3\\text4.txt")
    file9.mkdirs()
    file9_1.createNewFile()
    file9_2.createNewFile()
    file9_3.createNewFile()
    file9_4.createNewFile()
    file9_1.writeText("Voxidjonov Abduxalil")
    file9_2.writeText("Voxidjonov Abduxalil")
    file9_3.writeText("Voxidjonov Abduxalil")
    file9_4.writeText("Voxidjonov Abduxalil")

    val file10 = File("D:\\android1\\android2\\android2\\android1")
    val file10_1 = File("D:\\android1\\android2\\android2\\android1\\text1.txt")
    val file10_2 = File("D:\\android1\\android2\\android2\\android1\\text2.txt")
    val file10_3 = File("D:\\android1\\android2\\android2\\android1\\text3.txt")
    val file10_4 = File("D:\\android1\\android2\\android2\\android1\\text4.txt")
    file10.mkdirs()
    file10_1.createNewFile()
    file10_2.createNewFile()
    file10_3.createNewFile()
    file10_4.createNewFile()
    file10_1.writeText("Voxidjonov Abduxalil")
    file10_2.writeText("Voxidjonov Abduxalil")
    file10_3.writeText("Voxidjonov Abduxalil")
    file10_4.writeText("Voxidjonov Abduxalil")

    val file11 = File("D:\\android1\\android2\\android2\\android2")
    val file11_1 = File("D:\\android1\\android2\\android2\\android2\\text1.txt")
    val file11_2 = File("D:\\android1\\android2\\android2\\android2\\text2.txt")
    val file11_3 = File("D:\\android1\\android2\\android2\\android2\\text3.txt")
    val file11_4 = File("D:\\android1\\android2\\android2\\android2\\text4.txt")
    file11.mkdirs()
    file11_1.createNewFile()
    file11_2.createNewFile()
    file11_3.createNewFile()
    file11_4.createNewFile()
    file11_1.writeText("Voxidjonov Abduxalil")
    file11_2.writeText("Voxidjonov Abduxalil")
    file11_3.writeText("Voxidjonov Abduxalil")
    file11_4.writeText("Voxidjonov Abduxalil")

    val file12 = File("D:\\android1\\android2\\android2\\android3")
    val file12_1 = File("D:\\android1\\android2\\android2\\android3\\text1.txt")
    val file12_2 = File("D:\\android1\\android2\\android2\\android3\\text2.txt")
    val file12_3 = File("D:\\android1\\android2\\android2\\android3\\text3.txt")
    val file12_4 = File("D:\\android1\\android2\\android2\\android3\\text4.txt")

    file12.mkdirs()
    file12_1.createNewFile()
    file12_2.createNewFile()
    file12_3.createNewFile()
    file12_4.createNewFile()
    file12_1.writeText("Voxidjonov Abduxalil")
    file12_2.writeText("Voxidjonov Abduxalil")
    file12_3.writeText("Voxidjonov Abduxalil")
    file12_4.writeText("Voxidjonov Abduxalil")
}